### ISSUE TITLE
Some Issues/Suggestions

### ISSUE THREAD

**Issue by NekosakiSR** [jianxingxuejian/grasscutter-tools#1]
● The "Clear Bag" button doesn't clear artifacts, weapons, and some 5* mats _The in-game command clears everything no problem_
● In the Artifact tab, some artifacts only give 4* options, also there is no option to set the level of the artifact instead of editing it in the command. (_List of Artifacts Below_) 
- Echoes of an Offering
- Tenacity of the Millelith
- Wanderer's Troupe

Suggestions:
● Is it possible that you can make the "Level-up All" button the same way as the "Clear Bag" button? Being able to choose would be nice.
● Can you make the weather command look less complicated? Like have it set for current location or anything else.

_I am currently in the process of translating everything to English and fixing any grammar errors. I am only doing translations, as I am still taking my time learning how to code._

**Comment by jianxingxuejian** [comment]
1. i will fix it these day.
2. after finish the artifact generate, i didn' test all items, i will fix to right id, thank you.
3. a good idea, i will edit it as soon as possible.
4. about weather, use location name to replace the id seem a nice idea, but it will cost me too many time to name and do i18n, so the priority is low.

**Comment by jianxingxuejian** [comment]
@NekosakiSR "Clear Bag" button is same to the clear command, are you sure clear command can clear all items include 5* artifacts/weapons/mats?

**Comment by jianxingxuejian** [comment]
Closing this issue, if that problem is still not solved please open a separate issue.
About translation, i refactor i18n folder, If you are still willing to contribute, you can go there to translate the artifact detail, monster list probably also need to be beautified, is generated with a script.
Thanks for the previous help.
