### ISSUE TITLE
求问开发模式为什么跑不起来

### ISSUE THREAD

**Issue by ghostcatu** [jianxingxuejian/grasscutter-tools#10]
VITE v3.1.6  ready in 2713 ms

  ➜  Local:   https://localhost:3000/

 ELIFECYCLE  Command failed with exit code 4294967295.
       Error failed to get project out directory: failed to get cargo metadata: program not found
 ELIFECYCLE  Command failed with exit code 1.

**Comment by ghostcatu** [comment]
不是本地服务器，是我另一台电脑的服务器

**Comment by jianxingxuejian** [comment]
电脑上有rust和cargo环境吗？如果你是mac，安装完后还需要重启。

**Comment by ghostcatu** [comment]
> 如果你是mac，安装完之后还需要重启。

第一用这个，安装后可以启动了，谢谢你的回复。天体好看
