### ISSUE TITLE
使用管理员创建带有密码的账号，但是无法登录是否需要安装什么插件

### ISSUE THREAD

**Issue by ghostcatu** [jianxingxuejian/grasscutter-tools#11]
gc关闭了自动创建账号，使用管理员创建了一账号，客户端无法登录提示密码错误。查看了mongodb，密码和输入的一致。是否要安装其他插件配合使用呢

**Comment by jianxingxuejian** [comment]
我插件有段代码错了，待会更新下。如果还是解决不了那是另一个问题，客户端登录的密码是加密后的，在服务端要进行解密，3.0后解密方法会抛错，可能是客户端修补的问题，我没有使用密码的需求就没去研究。

**Comment by jianxingxuejian** [comment]
@ghostcatu 重新看了下代码发现没问题，那我这边是没地方修改了。
