### ISSUE TITLE
Clear all button doesn't clear everything

### ISSUE THREAD

**Issue by NekosakiSR** [jianxingxuejian/grasscutter-tools#13]
[Here's](https://streamable.com/mcm4o5) a video showing the issue #1 that's present

Anything with a level or refinement doesn't get deleted, and some 5* mats also. As you can see in the video, the normal clear command works normally.

**Comment by jianxingxuejian** [comment]
I read the source code, the default setting is lv1,refinement1,rank4 if not specified, so i should also provide these parameters to choose from. I will improve it in next version.
