### ISSUE TITLE
系统代理功能目前是否可用或是否需其他软件？

### ISSUE THREAD

**Issue by CCA2878** [jianxingxuejian/grasscutter-tools#21]
在任何说明中均未提及这两点，因而有此疑问。
经过测试，在Windows 10 专业工作站版 22H2中此设置未对系统代理做任何操作。

**Comment by jianxingxuejian** [comment]
配合Cultivation等软件使用时，它们会修改系统代理，可能造成我的客户端无法访问服务端，因此我加了个开关，默认情况下是关闭的，这样请求不会走系统代理，开启就是使用系统代理进行请求。

**Comment by CCA2878** [comment]
> 配合Cultivation等软件使用时，它们会修改系统代理，可能造成我的客户端无法访问服务端，因此我加了个开关，默认情况下是关闭的，这样请求不会走系统代理，开启就是使用系统代理进行请求。

感谢回复。如果我理解正确的话，这一设置项的实际作用是控制该工具的流量是否经过系统代理，而并非一种代理功能。
建议在wiki中添加说明或修改其label文本以更契合其实际功能，避免误解。

**Comment by jianxingxuejian** [comment]
🆗这个确实有歧义，后面我会修改
