### ISSUE TITLE
No way to add a port to Server Settings

### ISSUE THREAD

**Issue by Excadere** [jianxingxuejian/grasscutter-tools#23]
Not sure If I am missing something here, but if you're trying to join a server that's not using port 443 it seems you always get a Server IP error. I am using the : to signify a different port.

**Comment by jianxingxuejian** [comment]
Are you sure the server is running on another port? The default is 443, you can modify the server config to run on other ports.

**Comment by jianxingxuejian** [comment]
@Excadere I just did a test, the server side is modified to port 442, the client access through port 442 successfully, please confirm whether it is a firewall problem.

**Comment by Excadere** [comment]
I see, so it wasn't a firewall problem. The server I set up is using a subdomain name rather than a regular IP. So it seems SubDomainName:port does not work the same as IP:port. I guess that's just a lack of trying on my side.

**Comment by jianxingxuejian** [comment]
Can your game client connect to the GC server properly? You can try turning on or off the switch for the system proxy on the first page.

**Comment by Excadere** [comment]
My game can connect to the server, and if I use IP instead of subdomain name grasscutter tools can connect as well. The only issue I'm seeing now is every time I try to input the code sent to the mailbox I get network error. But that may be a separate issue.

**Comment by jianxingxuejian** [comment]
@Excadere I have no problem using subdomains now. I guess that there is a problem with your domain name resolution or server config.

**Comment by jianxingxuejian** [comment]
If in doubt open again.
