### ISSUE TITLE
3.3 3.4 mail system 無法使用 可否用其他認証方式

### ISSUE THREAD

**Issue by kamanya** [jianxingxuejian/grasscutter-tools#34]
目前下載到的 3.3 3.4 都無法用郵件認証(有寄成功 但無法讀信) 可否用遊戲裡的聊天方試認証
目前已在CMD看到证认码了 (看了DC上的教学)

**Comment by jianxingxuejian** [comment]
https://github.com/jianxingxuejian/grasscutter-plugin/releases/tag/v1.5.2
更新插件，新增了一个指令：`/verify` 同样可以获取验证码
暂时不要关闭这个问题，直到文档更新
