### ISSUE TITLE
還是無法驗証

### ISSUE THREAD

**Issue by kamanya** [jianxingxuejian/grasscutter-tools#37]
config.json
        "useEncryption": true,
        "useInRouting": true,
這兩個改成false了話
會無法進入原神(4204)
改成true 驗証會失敗 改成true才能進入原神
現在試 true  https又可以驗証.. 0.0 真的奇怪
目前是https
代理是用別人的 Launcher.exe 代理成功
目前沒有新聖遺物嗎? 3.3

**Comment by jianxingxuejian** [comment]
地址是http://ip:443吗，不能是https

**Comment by jianxingxuejian** [comment]
用的哪一个启动器？我还没解决https的问题，应该只有部署证书才能用。新的圣遗物忘加了，明天或者后天加。

**Comment by kamanya** [comment]
> 用的哪一个启动器？我还没解决https的问题，应该只有部署证书才能用。新的圣遗物忘加了，明天或者后天加。

swetyCore做的 但目前他的github是404

**Comment by jianxingxuejian** [comment]
如果是验证的话，true+https/false+http 443 都行，流量代理目前有点问题，最好在私人服务器使用http，或者自行部署证书也可以成功代理https，如果还是不行在discord@我
