### ISSUE TITLE
Win11家用版无法执行安装

### ISSUE THREAD

**Issue by kamanya** [jianxingxuejian/grasscutter-tools#4]
安装会出现  无法开启此封装,请确认是否为正常的Windows Installer封装

**Comment by jianxingxuejian** [comment]
@kamanya 尝试用管理员权限运行下，如果不行的话下载其他的tauri应用程序试看看有没有相同问题。

**Comment by jianxingxuejian** [comment]
关闭问题，如果没有解决再打开。
